#!/usr/bin/env bash

set -e

eval "$(opam env)"
echo "Building..." >&2
dune build
echo "Built binary at _build/default/bin/main.exe" >&2
touch _build/default/bin/main.exe # update timestamp to avoid rebuild with Makefile
